{"@t":"2022-02-14T07:44:11.9046772Z","@mt":"Failed (will repeat).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at NPoco.Database.OpenSharedConnectionImp(Boolean isInternal)\r\n   at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 330\r\n   at Umbraco.Core.Sync.DatabaseServerMessenger.Sync() in D:\\a\\1\\s\\src\\Umbraco.Core\\Sync\\DatabaseServerMessenger.cs:line 263\r\n   at Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent.InstructionProcessTask.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Compose\\DatabaseServerRegistrarAndMessengerComponent.cs:line 163\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20","SourceContext":"Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent+InstructionProcessTask","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":101,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-14T07:44:31.9937420Z","@mt":"Failed (will repeat).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at NPoco.Database.OpenSharedConnectionImp(Boolean isInternal)\r\n   at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 330\r\n   at Umbraco.Core.Sync.DatabaseServerMessenger.Sync() in D:\\a\\1\\s\\src\\Umbraco.Core\\Sync\\DatabaseServerMessenger.cs:line 263\r\n   at Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent.InstructionProcessTask.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Compose\\DatabaseServerRegistrarAndMessengerComponent.cs:line 163\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20","SourceContext":"Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent+InstructionProcessTask","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":90,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-14T07:44:37.0111886Z","@mt":"Failed (will repeat).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at NPoco.Database.OpenSharedConnectionImp(Boolean isInternal)\r\n   at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 330\r\n   at Umbraco.Core.Sync.DatabaseServerMessenger.Sync() in D:\\a\\1\\s\\src\\Umbraco.Core\\Sync\\DatabaseServerMessenger.cs:line 263\r\n   at Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent.InstructionProcessTask.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Compose\\DatabaseServerRegistrarAndMessengerComponent.cs:line 163\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20","SourceContext":"Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent+InstructionProcessTask","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":98,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-14T07:44:56.8269321Z","@mt":"Failed (will repeat).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at NPoco.Database.OpenSharedConnectionImp(Boolean isInternal)\r\n   at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 330\r\n   at Umbraco.Core.Sync.DatabaseServerMessenger.Sync() in D:\\a\\1\\s\\src\\Umbraco.Core\\Sync\\DatabaseServerMessenger.cs:line 263\r\n   at Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent.InstructionProcessTask.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Compose\\DatabaseServerRegistrarAndMessengerComponent.cs:line 163\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20","SourceContext":"Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent+InstructionProcessTask","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":96,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-14T07:44:57.5529794Z","@mt":"Failed.","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at NPoco.Database.OpenSharedConnectionImp(Boolean isInternal)\r\n   at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 330\r\n   at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.HasContentForRelease(DateTime date) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\Repositories\\Implement\\DocumentRepository.cs:line 1050\r\n   at Umbraco.Core.Services.Implement.ContentService.PerformScheduledPublishingRelease(DateTime date, List`1 results, EventMessages evtMsgs, Lazy`1 allLangs) in D:\\a\\1\\s\\src\\Umbraco.Core\\Services\\Implement\\ContentService.cs:line 1467\r\n   at Umbraco.Core.Services.Implement.ContentService.PerformScheduledPublish(DateTime date) in D:\\a\\1\\s\\src\\Umbraco.Core\\Services\\Implement\\ContentService.cs:line 1396\r\n   at Umbraco.Web.Scheduling.ScheduledPublishing.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\ScheduledPublishing.cs:line 68\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20","SourceContext":"Umbraco.Web.Scheduling.ScheduledPublishing","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":92,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-14T07:45:01.8390874Z","@mt":"Failed (will repeat).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at NPoco.Database.OpenSharedConnectionImp(Boolean isInternal)\r\n   at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 330\r\n   at Umbraco.Core.Sync.DatabaseServerMessenger.Sync() in D:\\a\\1\\s\\src\\Umbraco.Core\\Sync\\DatabaseServerMessenger.cs:line 263\r\n   at Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent.InstructionProcessTask.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Compose\\DatabaseServerRegistrarAndMessengerComponent.cs:line 163\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20","SourceContext":"Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent+InstructionProcessTask","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":96,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-14T07:45:06.8804692Z","@mt":"Failed (will repeat).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at NPoco.Database.OpenSharedConnectionImp(Boolean isInternal)\r\n   at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 330\r\n   at Umbraco.Core.Sync.DatabaseServerMessenger.Sync() in D:\\a\\1\\s\\src\\Umbraco.Core\\Sync\\DatabaseServerMessenger.cs:line 263\r\n   at Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent.InstructionProcessTask.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Compose\\DatabaseServerRegistrarAndMessengerComponent.cs:line 163\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20","SourceContext":"Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent+InstructionProcessTask","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":64,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-14T07:45:11.8961060Z","@mt":"Failed (will repeat).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at NPoco.Database.OpenSharedConnectionImp(Boolean isInternal)\r\n   at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 330\r\n   at Umbraco.Core.Sync.DatabaseServerMessenger.Sync() in D:\\a\\1\\s\\src\\Umbraco.Core\\Sync\\DatabaseServerMessenger.cs:line 263\r\n   at Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent.InstructionProcessTask.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Compose\\DatabaseServerRegistrarAndMessengerComponent.cs:line 163\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20","SourceContext":"Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent+InstructionProcessTask","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":89,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-14T07:51:28.4141717Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username oliver.gjesing@akqa.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":99,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":7,"HttpRequestId":"0ecc432e-2935-4895-80f4-d9d9ba3ba77f"}
{"@t":"2022-02-14T07:51:28.4141717Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: oliver.gjesing@akqa.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":99,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":7,"HttpRequestId":"0ecc432e-2935-4895-80f4-d9d9ba3ba77f"}
{"@t":"2022-02-14T07:51:40.7786321Z","@mt":"Exception","@l":"Error","@x":"ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 609 : No image exists at D:\\Users\\Oliver.Gjesing.EMEA\\Documents\\Git\\FTO\\BE\\Flight2Orbit\\media\\bddkxw1w\\9368855062_a548b9c5eb_o.jpg","SourceContext":"ImageProcessor.Web.HttpModules.ImageProcessingModule","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":110,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR","HttpRequestNumber":8,"HttpRequestId":"deacae7f-9bfc-4e4e-b9e5-ca73ab727f94"}
{"@t":"2022-02-14T07:59:00.2764644Z","@mt":"An error occurred during the index commit operation, if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"System.IO.FileNotFoundException: Could not find file 'D:\\Users\\Oliver.Gjesing.EMEA\\Documents\\Git\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\Internal\\_bg.fnm'.\r\nFile name: 'D:\\Users\\Oliver.Gjesing.EMEA\\Documents\\Git\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\Internal\\_bg.fnm'\r\n   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at Lucene.Net.Store.SimpleFSDirectory.OpenInput(String name, Int32 bufferSize) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Store\\SimpleFSDirectory.cs:line 72\r\n   at Lucene.Net.Index.FieldInfos..ctor(Directory d, String name) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\FieldInfos.cs:line 73\r\n   at Lucene.Net.Index.SegmentReader.CoreReaders..ctor(SegmentReader origInstance, Directory dir, SegmentInfo si, Int32 readBufferSize, Int32 termsIndexDivisor) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\SegmentReader.cs:line 125\r\n   at Lucene.Net.Index.SegmentReader.Get(Boolean readOnly, Directory dir, SegmentInfo si, Int32 readBufferSize, Boolean doOpenStores, Int32 termInfosIndexDivisor) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\SegmentReader.cs:line 779\r\n   at Lucene.Net.Index.IndexWriter.ReaderPool.Get(SegmentInfo info, Boolean doOpenStores, Int32 readBufferSize, Int32 termsIndexDivisor) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 689\r\n   at Lucene.Net.Index.IndexWriter.ReaderPool.Get(SegmentInfo info, Boolean doOpenStores) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 656\r\n   at Lucene.Net.Index.DocumentsWriter.ApplyDeletes(SegmentInfos infos) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\DocumentsWriter.cs:line 1265\r\n   at Lucene.Net.Index.IndexWriter.ApplyDeletes() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 5367\r\n   at Lucene.Net.Index.IndexWriter.DoFlushInternal(Boolean flushDocStores, Boolean flushDeletes) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4377\r\n   at Lucene.Net.Index.IndexWriter.DoFlush(Boolean flushDocStores, Boolean flushDeletes) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4197\r\n   at Lucene.Net.Index.IndexWriter.PrepareCommit(IDictionary`2 commitUserData) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4034\r\n   at Lucene.Net.Index.IndexWriter.Commit(IDictionary`2 commitUserData) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4116\r\n   at Examine.LuceneEngine.Providers.LuceneIndex.IndexCommiter.TimerRelease() in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\LuceneIndex.cs:line 1097","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":109,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-14T07:59:00.6568151Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _da: fieldsReader shows 65 but segmentInfo shows 1\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-14T07:59:05.4461007Z","@mt":"An error occurred during the index commit operation, if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"System.IO.FileNotFoundException: Could not find file 'D:\\Users\\Oliver.Gjesing.EMEA\\Documents\\Git\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\Internal\\_bg.fnm'.\r\nFile name: 'D:\\Users\\Oliver.Gjesing.EMEA\\Documents\\Git\\FTO\\BE\\Flight2Orbit\\App_Data\\TEMP\\ExamineIndexes\\Internal\\_bg.fnm'\r\n   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)\r\n   at Lucene.Net.Store.SimpleFSDirectory.OpenInput(String name, Int32 bufferSize) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Store\\SimpleFSDirectory.cs:line 72\r\n   at Lucene.Net.Index.FieldInfos..ctor(Directory d, String name) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\FieldInfos.cs:line 73\r\n   at Lucene.Net.Index.SegmentReader.CoreReaders..ctor(SegmentReader origInstance, Directory dir, SegmentInfo si, Int32 readBufferSize, Int32 termsIndexDivisor) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\SegmentReader.cs:line 125\r\n   at Lucene.Net.Index.SegmentReader.Get(Boolean readOnly, Directory dir, SegmentInfo si, Int32 readBufferSize, Boolean doOpenStores, Int32 termInfosIndexDivisor) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\SegmentReader.cs:line 779\r\n   at Lucene.Net.Index.IndexWriter.ReaderPool.Get(SegmentInfo info, Boolean doOpenStores, Int32 readBufferSize, Int32 termsIndexDivisor) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 689\r\n   at Lucene.Net.Index.IndexWriter.ReaderPool.Get(SegmentInfo info, Boolean doOpenStores) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 656\r\n   at Lucene.Net.Index.DocumentsWriter.ApplyDeletes(SegmentInfos infos) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\DocumentsWriter.cs:line 1265\r\n   at Lucene.Net.Index.IndexWriter.ApplyDeletes() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 5367\r\n   at Lucene.Net.Index.IndexWriter.DoFlushInternal(Boolean flushDocStores, Boolean flushDeletes) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4377\r\n   at Lucene.Net.Index.IndexWriter.DoFlush(Boolean flushDocStores, Boolean flushDeletes) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4197\r\n   at Lucene.Net.Index.IndexWriter.PrepareCommit(IDictionary`2 commitUserData) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4034\r\n   at Lucene.Net.Index.IndexWriter.Commit(IDictionary`2 commitUserData) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4116\r\n   at Examine.LuceneEngine.Providers.LuceneIndex.IndexCommiter.TimerRelease() in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\LuceneIndex.cs:line 1097","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":112,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-14T07:59:05.7134151Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _da: fieldsReader shows 65 but segmentInfo shows 1\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":70,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-14T07:59:06.0240050Z","@mt":"Concurrent merge failed for index: ExternalIndex if this error is persistent then index rebuilding is necessary","@l":"Error","@x":"Lucene.Net.Index.MergePolicy+MergeException: Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown. ---> Lucene.Net.Index.CorruptIndexException: doc counts differ for segment _da: fieldsReader shows 65 but segmentInfo shows 1\r\n   at Lucene.Net.Index.IndexWriter.HandleMergeException(Exception t, OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4641\r\n   at Lucene.Net.Index.IndexWriter.Merge(OneMerge merge) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\IndexWriter.cs:line 4674\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run() in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 370\r\n   --- End of inner exception stack trace ---\r\n   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc) in d:\\Lucene.Net\\FullRepo\\trunk\\src\\core\\Index\\ConcurrentMergeScheduler.cs:line 430\r\n   at Examine.LuceneEngine.Providers.ErrorLoggingConcurrentMergeScheduler.HandleMergeException(Exception exc) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\ErrorLoggingConcurrentMergeScheduler.cs:line 26","SourceContext":"Umbraco.Examine.UmbracoContentIndex","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":67,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-14T08:07:51.4787604Z","@mt":"Exception","@l":"Error","@x":"ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 609 : No image exists at D:\\Users\\Oliver.Gjesing.EMEA\\Documents\\Git\\FTO\\BE\\Flight2Orbit\\media\\bddkxw1w\\9368855062_a548b9c5eb_o.jpg","SourceContext":"ImageProcessor.Web.HttpModules.ImageProcessingModule","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":95,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR","HttpRequestNumber":9,"HttpRequestId":"2b9201ac-e897-4813-9aeb-58fb948f2433"}
{"@t":"2022-02-14T08:10:16.4871146Z","@mt":"Exception","@l":"Error","@x":"ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 609 : No image exists at D:\\Users\\Oliver.Gjesing.EMEA\\Documents\\Git\\FTO\\BE\\Flight2Orbit\\media\\bddkxw1w\\9368855062_a548b9c5eb_o.jpg","SourceContext":"ImageProcessor.Web.HttpModules.ImageProcessingModule","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":92,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR","HttpRequestNumber":10,"HttpRequestId":"dd1cdedb-6bb5-4b86-b010-b3c310f31d1b"}
{"@t":"2022-02-14T08:41:19.6827424Z","@mt":"Exception ({InstanceId}).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - The network connection was aborted by the local system.) ---> System.ComponentModel.Win32Exception (0x80004005): The network connection was aborted by the local system\r\n   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)\r\n   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()\r\n   at System.Data.SqlClient.SqlDataReader.get_MetaData()\r\n   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteScalar()\r\n   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryPolicy.cs:line 172\r\n   at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)\r\n   at NPoco.Database.ExecuteScalar[T](String sql, CommandType commandType, Object[] args)\r\n   at Umbraco.Core.Sync.DatabaseServerMessenger.PruneOldInstructions(IUmbracoDatabase database) in D:\\a\\1\\s\\src\\Umbraco.Core\\Sync\\DatabaseServerMessenger.cs:line 448\r\n   at Umbraco.Core.Sync.DatabaseServerMessenger.Sync() in D:\\a\\1\\s\\src\\Umbraco.Core\\Sync\\DatabaseServerMessenger.cs:line 282\r\n   at Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent.InstructionProcessTask.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Compose\\DatabaseServerRegistrarAndMessengerComponent.cs:line 163\r\nClientConnectionId:51b2ca68-8b65-48c2-9f3a-28cc8c16230b\r\nError Number:1236,State:0,Class:20","InstanceId":"6bd4531e","SourceContext":"Umbraco.Core.Persistence.UmbracoDatabase","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":67,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-14T08:41:34.4976706Z","@mt":"Failed.","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at NPoco.Database.OpenSharedConnectionImp(Boolean isInternal)\r\n   at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 330\r\n   at Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository.HasContentForRelease(DateTime date) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\Repositories\\Implement\\DocumentRepository.cs:line 1050\r\n   at Umbraco.Core.Services.Implement.ContentService.PerformScheduledPublishingRelease(DateTime date, List`1 results, EventMessages evtMsgs, Lazy`1 allLangs) in D:\\a\\1\\s\\src\\Umbraco.Core\\Services\\Implement\\ContentService.cs:line 1467\r\n   at Umbraco.Core.Services.Implement.ContentService.PerformScheduledPublish(DateTime date) in D:\\a\\1\\s\\src\\Umbraco.Core\\Services\\Implement\\ContentService.cs:line 1396\r\n   at Umbraco.Web.Scheduling.ScheduledPublishing.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\ScheduledPublishing.cs:line 68\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20","SourceContext":"Umbraco.Web.Scheduling.ScheduledPublishing","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":72,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-14T08:41:34.4976706Z","@mt":"Failed (will repeat).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.<>c__DisplayClass20_0.<ExecuteAction>b__0() in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryPolicy.cs:line 125\r\n   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryPolicy.cs:line 172\r\n   at NPoco.Database.AbortTransaction(Boolean fromComplete)\r\n   at Umbraco.Core.Scoping.Scope.DisposeLastScope() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 621\r\n   at Umbraco.Core.Scoping.Scope.Dispose() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 557\r\n   at Umbraco.Core.Sync.DatabaseServerMessenger.Sync() in D:\\a\\1\\s\\src\\Umbraco.Core\\Sync\\DatabaseServerMessenger.cs:line 283\r\n   at Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent.InstructionProcessTask.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Compose\\DatabaseServerRegistrarAndMessengerComponent.cs:line 163\r\nClientConnectionId:00000000-0000-0000-0000-000000000000\r\nError Number:53,State:0,Class:20","SourceContext":"Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent+InstructionProcessTask","ProcessId":18916,"ProcessName":"iisexpress","ThreadId":67,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-14T10:42:05.3020019Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Booting Umbraco 8.17.2.","TimingId":"5c8d2d7","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"2bb2c9f3-458e-478a-b5b0-ccd2049932ad"}
{"@t":"2022-02-14T10:42:05.3600050Z","@mt":"Booting site '{HostingSiteName}', app '{HostingApplicationID}', path '{HostingPhysicalPath}', server '{MachineName}'.","HostingSiteName":"Flight2Orbit","HostingApplicationID":"/LM/W3SVC/2/ROOT","HostingPhysicalPath":"D:\\Users\\Oliver.Gjesing.EMEA\\Documents\\Git\\FTO\\BE\\Flight2Orbit\\","MachineName":"AAR00118","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"2bb2c9f3-458e-478a-b5b0-ccd2049932ad"}
{"@t":"2022-02-14T10:42:05.6830036Z","@mt":"Acquiring.","SourceContext":"Umbraco.Core.Runtime.MainDom","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"2bb2c9f3-458e-478a-b5b0-ccd2049932ad"}
{"@t":"2022-02-14T10:42:05.6880088Z","@mt":"Acquired.","SourceContext":"Umbraco.Core.Runtime.MainDom","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"2bb2c9f3-458e-478a-b5b0-ccd2049932ad"}
{"@t":"2022-02-14T10:42:07.8420035Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Resolving composer types.","TimingId":"cdf357f","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"2bb2c9f3-458e-478a-b5b0-ccd2049932ad"}
{"@t":"2022-02-14T10:42:08.1140064Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Resolved.","Duration":270,"TimingId":"cdf357f","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"2bb2c9f3-458e-478a-b5b0-ccd2049932ad"}
{"@t":"2022-02-14T10:42:09.2829976Z","@mt":"Profiler is VoidProfiler, not profiling (must run debug mode to profile).","SourceContext":"Umbraco.Web.Logging.WebProfilerComponent","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"2bb2c9f3-458e-478a-b5b0-ccd2049932ad"}
{"@t":"2022-02-14T10:42:09.6010017Z","@mt":"Initializing Umbraco internal event handlers for cache refreshing.","SourceContext":"Umbraco.Web.Cache.DistributedCacheBinderComponent","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"2bb2c9f3-458e-478a-b5b0-ccd2049932ad"}
{"@t":"2022-02-14T10:42:09.7580033Z","@mt":"Adding examine event handlers for {RegisteredIndexers} index providers.","RegisteredIndexers":3,"SourceContext":"Umbraco.Web.Search.ExamineComponent","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"2bb2c9f3-458e-478a-b5b0-ccd2049932ad"}
{"@t":"2022-02-14T10:42:09.8810072Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Booted.","Duration":4610,"TimingId":"5c8d2d7","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"2bb2c9f3-458e-478a-b5b0-ccd2049932ad"}
{"@t":"2022-02-14T10:42:10.7840009Z","@mt":"New url {Url} detected, re-discovering application url.","Url":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"15833a21-cb0d-4b73-9fce-8868ae805336"}
{"@t":"2022-02-14T10:42:10.7880051Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":13,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"ff59c521-fa17-4566-8ba7-a5a9d9ece521"}
{"@t":"2022-02-14T10:42:10.7880051Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":6,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":4,"HttpRequestId":"e6d51768-ca55-4418-aa29-9866876e7d18"}
{"@t":"2022-02-14T10:42:10.7880051Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"15833a21-cb0d-4b73-9fce-8868ae805336"}
{"@t":"2022-02-14T10:42:10.7880051Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":16,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":5,"HttpRequestId":"d1996537-1e27-4e42-b549-2df77c8413ab"}
{"@t":"2022-02-14T10:42:11.9030074Z","@mt":"No last synced Id found, this generally means this is a new server/install. The server will build its caches and indexes, and then adjust its last synced Id to the latest found in the database and maintain cache updates based on that Id.","@l":"Warning","SourceContext":"Umbraco.Core.Sync.DatabaseServerMessenger","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":13,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"WARN ","HttpRequestNumber":3,"HttpRequestId":"ff59c521-fa17-4566-8ba7-a5a9d9ece521"}
{"@t":"2022-02-14T10:42:11.9340037Z","@mt":"Starting initialize async background thread.","SourceContext":"Umbraco.Web.Search.BackgroundIndexRebuilder","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":13,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"ff59c521-fa17-4566-8ba7-a5a9d9ece521"}
{"@t":"2022-02-14T10:42:12.0690016Z","@mt":"Registered with MainDom, localContentDbExists? {LocalContentDbExists}, localMediaDbExists? {LocalMediaDbExists}","LocalContentDbExists":true,"LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"15833a21-cb0d-4b73-9fce-8868ae805336"}
{"@t":"2022-02-14T10:42:12.0700011Z","@mt":"Creating the content store, localContentDbExists? {LocalContentDbExists}","LocalContentDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"15833a21-cb0d-4b73-9fce-8868ae805336"}
{"@t":"2022-02-14T10:42:12.0750048Z","@mt":"Creating the media store, localMediaDbExists? {LocalMediaDbExists}","LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"15833a21-cb0d-4b73-9fce-8868ae805336"}
{"@t":"2022-02-14T10:42:13.6390019Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading content from database","TimingId":"4247839","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"15833a21-cb0d-4b73-9fce-8868ae805336"}
{"@t":"2022-02-14T10:42:14.4929996Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":853,"TimingId":"4247839","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"15833a21-cb0d-4b73-9fce-8868ae805336"}
{"@t":"2022-02-14T10:42:14.5799994Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading media from database","TimingId":"65818cd","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"15833a21-cb0d-4b73-9fce-8868ae805336"}
{"@t":"2022-02-14T10:42:14.6829956Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":103,"TimingId":"65818cd","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"15833a21-cb0d-4b73-9fce-8868ae805336"}
{"@t":"2022-02-14T10:42:26.9862226Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username oliver.gjesing@akqa.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":6,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":6,"HttpRequestId":"5277cb1b-f747-455b-8d29-3f2f3268e903"}
{"@t":"2022-02-14T10:42:26.9872244Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: oliver.gjesing@akqa.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":6,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":6,"HttpRequestId":"5277cb1b-f747-455b-8d29-3f2f3268e903"}
{"@t":"2022-02-14T11:30:24.6252134Z","@mt":"Failed (will repeat).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - The network connection was aborted by the local system.) ---> System.ComponentModel.Win32Exception (0x80004005): The network connection was aborted by the local system\r\n   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)\r\n   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()\r\n   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)\r\n   at System.Data.SqlClient.TdsParser.TdsExecuteTransactionManagerRequest(Byte[] buffer, TransactionManagerRequestType request, String transactionName, TransactionManagerIsolationLevel isoLevel, Int32 timeout, SqlInternalTransaction transaction, TdsParserStateObject stateObj, Boolean isDelegateControlRequest)\r\n   at System.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransactionYukon(TransactionRequest transactionRequest, String transactionName, IsolationLevel iso, SqlInternalTransaction internalTransaction, Boolean isDelegateControlRequest)\r\n   at System.Data.SqlClient.SqlInternalConnection.BeginSqlTransaction(IsolationLevel iso, String transactionName, Boolean shouldReconnect)\r\n   at System.Data.SqlClient.SqlConnection.BeginTransaction(IsolationLevel iso, String transactionName)\r\n   at System.Data.SqlClient.SqlConnection.BeginDbTransaction(IsolationLevel isolationLevel)\r\n   at StackExchange.Profiling.Data.ProfiledDbConnection.BeginDbTransaction(IsolationLevel isolationLevel) in C:\\projects\\dotnet\\src\\MiniProfiler.Shared\\Data\\ProfiledDbConnection.cs:line 138\r\n   at NPoco.Database.BeginTransaction(IsolationLevel isolationLevel)\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 330\r\n   at Umbraco.Core.Sync.DatabaseServerMessenger.Sync() in D:\\a\\1\\s\\src\\Umbraco.Core\\Sync\\DatabaseServerMessenger.cs:line 263\r\n   at Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent.InstructionProcessTask.PerformRun() in D:\\a\\1\\s\\src\\Umbraco.Web\\Compose\\DatabaseServerRegistrarAndMessengerComponent.cs:line 163\r\nClientConnectionId:675da7c4-ee98-45dc-bd6b-7d749bd19bf1\r\nError Number:1236,State:0,Class:20","SourceContext":"Umbraco.Web.Compose.DatabaseServerRegistrarAndMessengerComponent+InstructionProcessTask","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":38,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"ERROR"}
{"@t":"2022-02-14T11:32:31.9215508Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username oliver.gjesing@akqa.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":37,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":7,"HttpRequestId":"10a46100-cdda-49f6-89b0-1d62e4fa0a35"}
{"@t":"2022-02-14T11:32:31.9215508Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: oliver.gjesing@akqa.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":37,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":7,"HttpRequestId":"10a46100-cdda-49f6-89b0-1d62e4fa0a35"}
{"@t":"2022-02-14T12:15:23.1053639Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username oliver.gjesing@akqa.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":46,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":8,"HttpRequestId":"c8a10dfd-1c20-42a3-b819-8807086bb44c"}
{"@t":"2022-02-14T12:15:23.1053639Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: oliver.gjesing@akqa.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":46,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":8,"HttpRequestId":"c8a10dfd-1c20-42a3-b819-8807086bb44c"}
{"@t":"2022-02-14T13:18:44.4235676Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":38,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":9,"HttpRequestId":"d8b2e8e2-31d4-4874-8a33-8519c7e11d51"}
{"@t":"2022-02-14T13:18:44.6085483Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":38,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":9,"HttpRequestId":"d8b2e8e2-31d4-4874-8a33-8519c7e11d51"}
{"@t":"2022-02-14T13:45:10.2921733Z","@mt":"Generate models now.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":53,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":10,"HttpRequestId":"74c2977a-f3e2-4929-b4b2-5c03f2e53f38"}
{"@t":"2022-02-14T13:45:10.5196946Z","@mt":"Generated.","SourceContext":"Umbraco.ModelsBuilder.Embedded.LiveModelsProvider","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":53,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":10,"HttpRequestId":"74c2977a-f3e2-4929-b4b2-5c03f2e53f38"}
{"@t":"2022-02-14T13:45:33.9436784Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username oliver.gjesing@akqa.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":38,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":11,"HttpRequestId":"a6cfa4a5-4c59-455f-b89e-161520adf4f6"}
{"@t":"2022-02-14T13:45:33.9436784Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: oliver.gjesing@akqa.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":25552,"ProcessName":"iisexpress","ThreadId":38,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":11,"HttpRequestId":"a6cfa4a5-4c59-455f-b89e-161520adf4f6"}
{"@t":"2022-02-14T13:51:23.8957617Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Booting Umbraco 8.17.2.","TimingId":"940e931","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"e60422be-ccf0-4d47-937b-4cc808e8573c"}
{"@t":"2022-02-14T13:51:23.9257281Z","@mt":"Booting site '{HostingSiteName}', app '{HostingApplicationID}', path '{HostingPhysicalPath}', server '{MachineName}'.","HostingSiteName":"Flight2Orbit","HostingApplicationID":"/LM/W3SVC/2/ROOT","HostingPhysicalPath":"D:\\Users\\Oliver.Gjesing.EMEA\\Documents\\Git\\FTO\\BE\\Flight2Orbit\\","MachineName":"AAR00118","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"e60422be-ccf0-4d47-937b-4cc808e8573c"}
{"@t":"2022-02-14T13:51:24.0517255Z","@mt":"Acquiring.","SourceContext":"Umbraco.Core.Runtime.MainDom","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"e60422be-ccf0-4d47-937b-4cc808e8573c"}
{"@t":"2022-02-14T13:51:24.0537294Z","@mt":"Acquired.","SourceContext":"Umbraco.Core.Runtime.MainDom","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"e60422be-ccf0-4d47-937b-4cc808e8573c"}
{"@t":"2022-02-14T13:51:25.1094910Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Resolving composer types.","TimingId":"d756038","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"e60422be-ccf0-4d47-937b-4cc808e8573c"}
{"@t":"2022-02-14T13:51:25.2374795Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Resolved.","Duration":126,"TimingId":"d756038","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"e60422be-ccf0-4d47-937b-4cc808e8573c"}
{"@t":"2022-02-14T13:51:25.8461381Z","@mt":"Profiler is VoidProfiler, not profiling (must run debug mode to profile).","SourceContext":"Umbraco.Web.Logging.WebProfilerComponent","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"e60422be-ccf0-4d47-937b-4cc808e8573c"}
{"@t":"2022-02-14T13:51:26.0454730Z","@mt":"Initializing Umbraco internal event handlers for cache refreshing.","SourceContext":"Umbraco.Web.Cache.DistributedCacheBinderComponent","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"e60422be-ccf0-4d47-937b-4cc808e8573c"}
{"@t":"2022-02-14T13:51:26.1333930Z","@mt":"Adding examine event handlers for {RegisteredIndexers} index providers.","RegisteredIndexers":3,"SourceContext":"Umbraco.Web.Search.ExamineComponent","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"e60422be-ccf0-4d47-937b-4cc808e8573c"}
{"@t":"2022-02-14T13:51:26.2023618Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Booted.","Duration":2321,"TimingId":"940e931","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"e60422be-ccf0-4d47-937b-4cc808e8573c"}
{"@t":"2022-02-14T13:51:26.6726592Z","@mt":"New url {Url} detected, re-discovering application url.","Url":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":10,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"1e9d6d3b-36fe-4e92-be87-369c6ced6b8f"}
{"@t":"2022-02-14T13:51:26.6726592Z","@mt":"New url {Url} detected, re-discovering application url.","Url":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"e9dac6a0-b861-4b2b-b2ab-82a43dc4c625"}
{"@t":"2022-02-14T13:51:26.6746564Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":10,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"1e9d6d3b-36fe-4e92-be87-369c6ced6b8f"}
{"@t":"2022-02-14T13:51:26.6746564Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://localhost:54252/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"e9dac6a0-b861-4b2b-b2ab-82a43dc4c625"}
{"@t":"2022-02-14T13:51:27.2966551Z","@mt":"No last synced Id found, this generally means this is a new server/install. The server will build its caches and indexes, and then adjust its last synced Id to the latest found in the database and maintain cache updates based on that Id.","@l":"Warning","SourceContext":"Umbraco.Core.Sync.DatabaseServerMessenger","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"WARN ","HttpRequestNumber":3,"HttpRequestId":"e9dac6a0-b861-4b2b-b2ab-82a43dc4c625"}
{"@t":"2022-02-14T13:51:27.3266537Z","@mt":"Forcing index {IndexerName} to be unlocked since it was left in a locked state","IndexerName":"InternalIndex","SourceContext":"Umbraco.Examine.ExamineExtensions","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"e9dac6a0-b861-4b2b-b2ab-82a43dc4c625"}
{"@t":"2022-02-14T13:51:27.3276545Z","@mt":"Forcing index {IndexerName} to be unlocked since it was left in a locked state","IndexerName":"MembersIndex","SourceContext":"Umbraco.Examine.ExamineExtensions","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"e9dac6a0-b861-4b2b-b2ab-82a43dc4c625"}
{"@t":"2022-02-14T13:51:27.3276545Z","@mt":"Forcing index {IndexerName} to be unlocked since it was left in a locked state","IndexerName":"ExternalIndex","SourceContext":"Umbraco.Examine.ExamineExtensions","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"e9dac6a0-b861-4b2b-b2ab-82a43dc4c625"}
{"@t":"2022-02-14T13:51:27.3296569Z","@mt":"Starting initialize async background thread.","SourceContext":"Umbraco.Web.Search.BackgroundIndexRebuilder","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"e9dac6a0-b861-4b2b-b2ab-82a43dc4c625"}
{"@t":"2022-02-14T13:51:27.3656560Z","@mt":"Registered with MainDom, localContentDbExists? {LocalContentDbExists}, localMediaDbExists? {LocalMediaDbExists}","LocalContentDbExists":true,"LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":10,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"1e9d6d3b-36fe-4e92-be87-369c6ced6b8f"}
{"@t":"2022-02-14T13:51:27.3666565Z","@mt":"Creating the content store, localContentDbExists? {LocalContentDbExists}","LocalContentDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":10,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"1e9d6d3b-36fe-4e92-be87-369c6ced6b8f"}
{"@t":"2022-02-14T13:51:27.3696588Z","@mt":"Creating the media store, localMediaDbExists? {LocalMediaDbExists}","LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":10,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"1e9d6d3b-36fe-4e92-be87-369c6ced6b8f"}
{"@t":"2022-02-14T13:51:28.2626571Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading content from database","TimingId":"c8b41bc","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":10,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"1e9d6d3b-36fe-4e92-be87-369c6ced6b8f"}
{"@t":"2022-02-14T13:51:28.7480953Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":485,"TimingId":"c8b41bc","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":10,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"1e9d6d3b-36fe-4e92-be87-369c6ced6b8f"}
{"@t":"2022-02-14T13:51:28.8061321Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading media from database","TimingId":"93f185e","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":10,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"1e9d6d3b-36fe-4e92-be87-369c6ced6b8f"}
{"@t":"2022-02-14T13:51:28.8797512Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":72,"TimingId":"93f185e","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":27240,"ProcessName":"iisexpress","ThreadId":10,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"AAR00118","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"1e9d6d3b-36fe-4e92-be87-369c6ced6b8f"}
